import type { SchemaResponse, CalculatorMetadata, HistoryItem, FormValues } from '../types';

export const MOCK_SCHEMA: SchemaResponse = {
  available_versions: ['v1', 'v2'],
  current_version: 'v2',
  ui_schema: {
    form_blocks: [
      {
        block_name: 'Общая информация',
        fields: [
          {
            id: 'Возраст (лет)',
            label: 'Возраст (лет)',
            type: 'number',
            order: 1,
            min: 0,
            max: 120,
            step: null,
            placeholder: 'Пример: 65',
            options: [],
          },
          {
            id: 'Пол (0=жен,1=муж)',
            label: 'Пол',
            type: 'select',
            order: 2,
            min: null,
            max: null,
            step: null,
            placeholder: '',
            options: [
              { value: 0, label: 'Женский' },
              { value: 1, label: 'Мужской' },
            ],
          },
          {
            id: 'Рост (м)',
            label: 'Рост (м)',
            type: 'number',
            order: 3,
            min: 0.5,
            max: 2.5,
            step: 0.01,
            placeholder: 'Пример: 1.75',
            options: [],
          },
          {
            id: 'Вес (кг)',
            label: 'Вес (кг)',
            type: 'number',
            order: 4,
            min: 10,
            max: 250,
            step: null,
            placeholder: 'Пример: 80',
            options: [],
          },
        ],
      },
      {
        block_name: 'Анамнез и коморбидность',
        fields: [
          {
            id: 'Гипертония (0/1)',
            label: 'Артериальная гипертензия',
            type: 'boolean',
            order: 5,
            min: null,
            max: null,
            step: null,
            placeholder: '',
            options: [],
          },
          {
            id: 'Сахарный диабет (0/1)',
            label: 'Сахарный диабет',
            type: 'boolean',
            order: 6,
            min: null,
            max: null,
            step: null,
            placeholder: '',
            options: [],
          },
          {
            id: 'ХОБЛ (0/1)',
            label: 'ХОБЛ',
            type: 'boolean',
            order: 7,
            min: null,
            max: null,
            step: null,
            placeholder: '',
            options: [],
          },
          {
            id: 'ИМ в анамнезе (0/1)',
            label: 'Инфаркт миокарда в анамнезе',
            type: 'boolean',
            order: 8,
            min: null,
            max: null,
            step: null,
            placeholder: '',
            options: [],
          },
          {
            id: 'ХСН (0/1)',
            label: 'Хроническая сердечная недостаточность',
            type: 'boolean',
            order: 9,
            min: null,
            max: null,
            step: null,
            placeholder: '',
            options: [],
          },
          {
            id: 'Лёгочная гипертензия (0/1)',
            label: 'Лёгочная гипертензия',
            type: 'boolean',
            order: 10,
            min: null,
            max: null,
            step: null,
            placeholder: '',
            options: [],
          },
          {
            id: 'ФП в анамнезе (0/1)',
            label: 'Фибрилляция предсердий в анамнезе',
            type: 'boolean',
            order: 11,
            min: null,
            max: null,
            step: null,
            placeholder: '',
            options: [],
          },
          {
            id: 'ОНМК в анамнезе (0/1)',
            label: 'ОНМК в анамнезе',
            type: 'boolean',
            order: 12,
            min: null,
            max: null,
            step: null,
            placeholder: '',
            options: [],
          },
          {
            id: 'Атеросклероз НК (0/1)',
            label: 'Атеросклероз нижних конечностей',
            type: 'boolean',
            order: 13,
            min: null,
            max: null,
            step: null,
            placeholder: '',
            options: [],
          },
          {
            id: 'Атеросклероз БЦА (0/1)',
            label: 'Атеросклероз БЦА',
            type: 'boolean',
            order: 14,
            min: null,
            max: null,
            step: null,
            placeholder: '',
            options: [],
          },
          {
            id: 'Язвенная болезнь ЖКТ (0/1)',
            label: 'Язвенная болезнь ЖКТ',
            type: 'boolean',
            order: 15,
            min: null,
            max: null,
            step: null,
            placeholder: '',
            options: [],
          },
        ],
      },
      {
        block_name: 'Статус операции и кардиометрия',
        fields: [
          {
            id: 'pump',
            label: 'Искусственное кровообращение (ИК)',
            type: 'boolean',
            order: 16,
            min: null,
            max: null,
            step: null,
            placeholder: '',
            options: [],
          },
          {
            id: 'Срочность (0=план,1=экстр)',
            label: 'Срочность операции',
            type: 'select',
            order: 17,
            min: null,
            max: null,
            step: null,
            placeholder: '',
            options: [
              { value: 0, label: 'Плановая' },
              { value: 1, label: 'Экстренная' },
            ],
          },
          {
            id: 'Категория ФВ ЛЖ',
            label: 'Категория ФВ ЛЖ',
            type: 'select',
            order: 18,
            min: null,
            max: null,
            step: null,
            placeholder: '',
            options: [
              { value: 1, label: 'Нормальная (≥50%)' },
              { value: 2, label: 'Умеренно сниженная (30-49%)' },
              { value: 3, label: 'Низкая (<30%)' },
            ],
          },
          {
            id: 'ХСН ФК',
            label: 'ХСН Функциональный класс',
            type: 'select',
            order: 19,
            min: null,
            max: null,
            step: null,
            placeholder: '',
            options: [
              { value: 0, label: 'Нет ХСН' },
              { value: 1, label: 'I ФК' },
              { value: 2, label: 'II ФК' },
              { value: 3, label: 'III ФК' },
              { value: 4, label: 'IV ФК' },
            ],
          },
        ],
      },
      {
        block_name: 'Лабораторные показатели',
        fields: [
          {
            id: 'Креатинин в ОРИТ (мкмоль/л)',
            label: 'Креатинин (мкмоль/л)',
            type: 'number',
            order: 20,
            min: 0,
            max: 2000,
            step: null,
            placeholder: 'Введите значение...',
            options: [],
          },
        ],
      },
    ],
    calculated_metrics_needed: ['EuroSCORE II (%)'],
  },
};

export const MOCK_CALCULATOR_METADATA: CalculatorMetadata = {
  required_inputs: [
    'Пол (0=жен,1=муж)',
    'Возраст (лет)',
    'Вес (кг)',
    'Рост (м)',
    'Креатинин в ОРИТ (мкмоль/л)',
    'Категория ФВ ЛЖ',
    'ХСН ФК',
    'Лёгочная гипертензия (0/1)',
    'Гипертония (0/1)',
    'ФП в анамнезе (0/1)',
    'ИМ в анамнезе (0/1)',
    'ХСН (0/1)',
    'Сахарный диабет (0/1)',
    'ХОБЛ (0/1)',
    'ОНМК в анамнезе (0/1)',
    'Атеросклероз НК (0/1)',
    'Атеросклероз БЦА (0/1)',
    'Язвенная болезнь ЖКТ (0/1)',
    'Срочность (0=план,1=экстр)',
    'pump',
  ],
  categorical_inputs: [
    'Пол (0=жен,1=муж)',
    'Категория ФВ ЛЖ',
    'ХСН ФК',
    'Лёгочная гипертензия (0/1)',
    'Гипертония (0/1)',
    'ФП в анамнезе (0/1)',
    'ИМ в анамнезе (0/1)',
    'ХСН (0/1)',
    'Сахарный диабет (0/1)',
    'ХОБЛ (0/1)',
    'ОНМК в анамнезе (0/1)',
    'Атеросклероз НК (0/1)',
    'Атеросклероз БЦА (0/1)',
    'Язвенная болезнь ЖКТ (0/1)',
    'Срочность (0=план,1=экстр)',
    'pump',
  ],
  calculators: {
    bmi: {
      label: 'Индекс массы тела (ИМТ)',
      required_inputs: ['Вес (кг)', 'Рост (м)'],
    },
    clcr: {
      label: 'Клиренс креатинина (Кокрофт-Голт)',
      required_inputs: [
        'Пол (0=жен,1=муж)',
        'Возраст (лет)',
        'Вес (кг)',
        'Креатинин в ОРИТ (мкмоль/л)',
      ],
    },
    euroscore: {
      label: 'EuroSCORE II',
      required_inputs: [
        'Возраст (лет)',
        'Пол (0=жен,1=муж)',
        'Вес (кг)',
        'Креатинин в ОРИТ (мкмоль/л)',
        'Атеросклероз НК (0/1)',
        'Атеросклероз БЦА (0/1)',
        'ХОБЛ (0/1)',
        'Сахарный диабет (0/1)',
        'Срочность (0=план,1=экстр)',
        'ХСН ФК',
        'Категория ФВ ЛЖ',
        'Лёгочная гипертензия (0/1)',
      ],
    },
    cci: {
      label: 'Индекс коморбидности Чарлсона',
      required_inputs: [
        'Возраст (лет)',
        'Пол (0=жен,1=муж)',
        'Вес (кг)',
        'Креатинин в ОРИТ (мкмоль/л)',
        'ИМ в анамнезе (0/1)',
        'ХСН (0/1)',
        'Категория ФВ ЛЖ',
        'Атеросклероз НК (0/1)',
        'Атеросклероз БЦА (0/1)',
        'ОНМК в анамнезе (0/1)',
        'ХОБЛ (0/1)',
        'Язвенная болезнь ЖКТ (0/1)',
        'Сахарный диабет (0/1)',
      ],
    },
  },
};

export const MOCK_DEMO_DATA: FormValues = {
  'Возраст (лет)': 65,
  'Пол (0=жен,1=муж)': 1,
  'Рост (м)': 1.75,
  'Вес (кг)': 82,
  'Гипертония (0/1)': 1,
  'Сахарный диабет (0/1)': 0,
  'ХОБЛ (0/1)': 0,
  'ИМ в анамнезе (0/1)': 0,
  'ХСН (0/1)': 1,
  'Лёгочная гипертензия (0/1)': 0,
  'ФП в анамнезе (0/1)': 1,
  'ОНМК в анамнезе (0/1)': 0,
  'Атеросклероз НК (0/1)': 0,
  'Атеросклероз БЦА (0/1)': 0,
  'Язвенная болезнь ЖКТ (0/1)': 0,
  'pump': 1,
  'Срочность (0=план,1=экстр)': 0,
  'Категория ФВ ЛЖ': 1,
  'ХСН ФК': 2,
  'Креатинин в ОРИТ (мкмоль/л)': 95,
};

export const generateMockHistory = (count: number = 20): HistoryItem[] => {
  const levels: ('low' | 'medium' | 'high' | 'danger')[] = ['low', 'medium', 'high', 'danger'];
  const versions = ['v1', 'v2'];
  
  return Array.from({ length: count }, (_, i) => {
    const level = levels[Math.floor(Math.random() * levels.length)];
    const scoreRanges = {
      low: [0.01, 0.15],
      medium: [0.15, 0.35],
      high: [0.35, 0.60],
      danger: [0.60, 0.95],
    };
    const [min, max] = scoreRanges[level];
    const score = min + Math.random() * (max - min);
    
    const date = new Date();
    date.setDate(date.getDate() - Math.floor(Math.random() * 90));
    
    return {
      id: 1000 + i,
      prediction_id: 1000 + i,
      patient_id: Math.floor(Math.random() * 500) + 1,
      operation_id: Math.floor(Math.random() * 300) + 1,
      risk_score: score,
      risk_level: level,
      model_version: versions[Math.floor(Math.random() * versions.length)],
      created_at: date.toISOString(),
      features: { ...MOCK_DEMO_DATA },
    };
  }).sort((a, b) => new Date(b.created_at).getTime() - new Date(a.created_at).getTime());
};

export const generateMockCalculatorResults = (): { status: string; metrics: Record<string, { value: number; label: string; level: 'low' | 'medium' | 'high' | 'danger' }> } => ({
  status: 'success',
  metrics: {
    BMI: {
      value: 26.78,
      label: 'Индекс массы тела: избыточная масса тела',
      level: 'medium',
    },
    ClCr: {
      value: 68.5,
      label: 'Клиренс креатинина: умеренное снижение функции почек',
      level: 'medium',
    },
    'EuroSCORE II': {
      value: 0.0234,
      label: 'Прогнозируемая операционная летальность: низкий риск',
      level: 'low',
    },
    CCI: {
      value: 4,
      label: 'Индекс Чарлсона: средний 10-летний прогноз выживаемости 53%',
      level: 'medium',
    },
  },
});
