-- Database initialization script for PostgreSQL
-- Creates tables and initial data

-- Create extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pg_trgm";

-- Set timezone
SET timezone = 'UTC';

-- Create tables (SQLAlchemy will handle this, but this is a backup)
-- The backend will create tables automatically from models

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_patients_created_at ON patients(created_at);
CREATE INDEX IF NOT EXISTS idx_operations_patient_id ON operations(patient_id);
CREATE INDEX IF NOT EXISTS idx_operations_created_at ON operations(created_at);
CREATE INDEX IF NOT EXISTS idx_clinical_data_operation_id ON clinical_data(operation_id);
CREATE INDEX IF NOT EXISTS idx_predictions_operation_id ON predictions(operation_id);
CREATE INDEX IF NOT EXISTS idx_predictions_created_at ON predictions(created_at);

-- Comments on tables
COMMENT ON TABLE patients IS 'Patient information for risk prediction system';
COMMENT ON TABLE operations IS 'Surgical operations performed on patients';
COMMENT ON TABLE clinical_data IS 'Clinical features and data for operations';
COMMENT ON TABLE predictions IS 'Risk predictions generated by the ML model';
